-- Specs require game modules via game.* paths (NOT relative) so every module
-- resolves to the single copy installed into the runtests DataModel.
return function(t)
	local CoreGui = game:GetService("CoreGui")
	local ReactRoblox = require(game.ReplicatedStorage.Packages.ReactRoblox)
	local DialogueView = require(game.ReplicatedStorage.DialogueView)

	local function withView(fn)
		local screen = Instance.new("ScreenGui")
		screen.Parent = CoreGui
		local view
		ReactRoblox.act(function()
			view = DialogueView.new()
		end)
		view:GetGui().Parent = screen
		local ok, err = pcall(fn, view, view:GetGui())
		ReactRoblox.act(function()
			view:Destroy()
		end)
		screen:Destroy()
		if not ok then
			error(err, 0)
		end
	end

	t.test("mounts with the template structure", function()
		withView(function(view, gui)
			t.expect(gui.ClassName).toBe("Frame")
			t.expect(gui.ChatBox.WindowTitle.Text).toBe("Netmap Chat")
			t.expect(gui.MouseCatcher.Visible).toBeTruthy()
			t.expect(gui.ChatBox.Inset.Content.Text).toBe("")
			t.expect(gui.ChatBox.Button1.Visible).toBeFalsy()
			t.expect(gui.ChatBox.Button2.Visible).toBeFalsy()
		end)
	end)

	t.test("the chat box hides while it has no content", function()
		withView(function(view, gui)
			-- Nothing set yet: chrome stays hidden
			t.expect(gui.ChatBox.Visible).toBeFalsy()
			ReactRoblox.act(function()
				view:SetText("Hello there")
			end)
			t.expect(gui.ChatBox.Visible).toBeTruthy()
			-- Clearing the text (tutorial between-steps state) hides it again
			ReactRoblox.act(function()
				view:SetText("")
			end)
			t.expect(gui.ChatBox.Visible).toBeFalsy()
		end)
	end)

	t.test("SetText with no choices hides both buttons and grows the inset", function()
		withView(function(view, gui)
			ReactRoblox.act(function()
				view:SetText("Hello there")
			end)
			t.expect(gui.ChatBox.Inset.Content.Text).toBe("Hello there")
			-- The typewriter starts from zero revealed characters (the full
			-- text is in the label; MaxVisibleGraphemes reveals it over time)
			t.expect(gui.ChatBox.Inset.Content.MaxVisibleGraphemes).toBe(0)
			t.expect(gui.ChatBox.Button1.Visible).toBeFalsy()
			t.expect(gui.ChatBox.Button2.Visible).toBeFalsy()
			t.expect(gui.ChatBox.Inset.Size).toBe(UDim2.new(1, -10, 1, -29))
		end)
	end)

	t.test("SetText with one choice shows only button 1", function()
		withView(function(view, gui)
			ReactRoblox.act(function()
				view:SetText("Pick", "OK")
			end)
			t.expect(gui.ChatBox.Button1.Visible).toBeTruthy()
			t.expect(gui.ChatBox.Button2.Visible).toBeFalsy()
			t.expect(gui.ChatBox.Button1.Text.Text).toBe("OK")
			t.expect(gui.ChatBox.Inset.Size).toBe(UDim2.new(1, -10, 1, -66))
		end)
	end)

	t.test("SetText with two choices shows both buttons with swapped labels", function()
		withView(function(view, gui)
			ReactRoblox.act(function()
				view:SetText("Pick one", "First", "Second")
			end)
			t.expect(gui.ChatBox.Button1.Visible).toBeTruthy()
			t.expect(gui.ChatBox.Button2.Visible).toBeTruthy()
			-- Button 2 is the top button and shows the first choice
			t.expect(gui.ChatBox.Button2.Text.Text).toBe("First")
			t.expect(gui.ChatBox.Button1.Text.Text).toBe("Second")
			t.expect(gui.ChatBox.Inset.Size).toBe(UDim2.new(1, -10, 1, -98))
		end)
	end)

	t.test("SetText back to fewer choices hides buttons again", function()
		withView(function(view, gui)
			ReactRoblox.act(function()
				view:SetText("Pick one", "First", "Second")
			end)
			ReactRoblox.act(function()
				view:SetText("Done now")
			end)
			t.expect(gui.ChatBox.Button1.Visible).toBeFalsy()
			t.expect(gui.ChatBox.Button2.Visible).toBeFalsy()
			t.expect(gui.ChatBox.Inset.Size).toBe(UDim2.new(1, -10, 1, -29))
		end)
	end)

	t.test("SetUser puts the name in the title and the picture in the body", function()
		withView(function(view, gui)
			ReactRoblox.act(function()
				view:SetUser("Vexedly", "rbxassetid://1352624214")
			end)
			t.expect(gui.ChatBox.WindowTitle.Text).toBe("Netmap Chat - Vexedly")
			t.expect(gui.ChatBox.Inset.ProfilePic.Image).toBe("rbxassetid://1352624214")
		end)
	end)

	t.test("SetTutorial retitles the window and hides the mouse catcher", function()
		withView(function(view, gui)
			ReactRoblox.act(function()
				view:SetTutorial()
			end)
			t.expect(gui.ChatBox.WindowTitle.Text).toBe("Game Chat")
			t.expect(gui.MouseCatcher.Visible).toBeFalsy()
			t.expect(gui.ChatBox.AnchorPoint).toBe(Vector2.new(1, 1))
		end)
	end)

	t.test("SetVisible toggles the host frame", function()
		withView(function(view, gui)
			view:SetVisible(false)
			t.expect(gui.Visible).toBeFalsy()
			view:SetVisible(true)
			t.expect(gui.Visible).toBeTruthy()
		end)
	end)
end
